site_name: Сайт-портфолио Жохова Даниила в пятницу 13-ое
nav:
    - Home: index.md
    - About: about.md
    - Lab Works:
        - Lab work 1: labwork1.md
        - Lab work 2: labwork2.md
        - Lab work 3: labwork3.md
theme:
    name: torillic