site_name: Сайт-портфолио Жохова Даниила в пятницу 13-ое
nav:
    - Home: index.md
    - About Me: about.md
    - Lab Works:
        - LIST OF WORKS: labworks/index.md
        - Lab work 1: labworks/lab1.md
        - Lab work 2: labworks/lab2.md
        - Lab work 3: labworks/lab3.md

markdown_extensions:
  - pymdownx.highlight:   # Подсветка кода
      anchor_linenums: true
  - pymdownx.superfences  # Блоки кода с языком
  - tables                # Таблицы
  - toc:                  # Оглавление на странице
      permalink: true

theme:
    name: kpn

extra_css:
  - css/custom.css